version: 1.0.0{build}

build:
  parallel: true
  verbosity: minimal

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCHITECTURE: x64
      GEN: "Visual Studio 15 2017 Win64"
      CFG: Release
      BUILD_OUT: "x64-Release"
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
  MSVC_HOME: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community"

install:
  # Get Ninja
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\ninja > nul
  - set PATH=C:\ninja;%PATH%
  - ninja --version

build_script:
  - call "%MSVC_HOME%\VC\Auxiliary\Build\vcvarsall.bat" %ARCHITECTURE%
  - mkdir Build\%BUILD_OUT% && cd Build\%BUILD_OUT%
  - cmake -DCMAKE_BUILD_TYPE=%CFG% -GNinja ../../
  - ninja
  - ninja install
  - cd ../../
